backend:
  name: github
  repo: yurigamui/lottusfinance
  branch: main
  auth_type: pkce
  app_id: "Ov23liDmBovLud1VJMWO" # Cole a chave que você gerou no GitHub (mantenha as aspas)

# Como a Lottus fará upload de imagens
media_folder: "public/assets/img/blog" # Onde as imagens ficam salvas no código
public_folder: "/assets/img/blog"      # O caminho que aparece no site final

# Customização visual do painel com as cores da Lottus
logo_url: "https://lottusfinance.com.br/assets/img/Logo%201.png"

# Coleções (O que pode ser postado)
collections:
  - name: "artigos"
    label: "Artigos do Blog"
    folder: "src/content/blog" # Onde o Astro vai buscar os textos em Markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Equipe Lottus" }
      - { label: "Imagem de Capa", name: "image", widget: "image", required: false }
      - { label: "Resumo (SEO)", name: "description", widget: "text" }
      - { label: "Corpo do Texto", name: "body", widget: "markdown" }